[package]
name = "aether-service-bus"
description = "Aether Service Bus for internal service communication."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aether-events.workspace = true
aether-ids.workspace = true
aether-permissions.workspace = true
aether-service.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
